### ISSUE TITLE
Coreferee Pipeline Update

### ISSUE THREAD

**Issue by DrLynch** [ArgLab/AWE_Workbench#4]
The Coreferee pipeline needs to be updated to handle new versions of spacy.  This will be a necessary prerequisite to the spacy updates.  Doing so will likely require changes both to this codebase and to the coreferee package.  The steps for this are discussed here:

https://github.com/richardpaulhudson/coreferee/issues/29#issuecomment-1901058334

**Comment by duckduckdoof** [comment]
Larger context for issues is addressed in #9
